services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./data/adguard/:/opt/adguardhome/work
      - ./data/adguard/:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "8843:443/tcp"
      - "443:443/udp"
      - "8830:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    networks:
      dns_network:
        ipv4_address: 172.30.0.4  # IP fixe dans le sous-réseau correct (par exemple)

  bind9:
    image: ubuntu/bind9:latest
    container_name: bind-dns
    environment:
      - BIND9_USER=root
      - TZ=Europe/Paris
    ports:
      - "553:53/tcp"
      - "553:53/udp"
    volumes:
      - ./data/bind9:/etc/bind
      - ./data/bind9/named.conf.options:/etc/bind/named.conf.options:ro
      - ./data/bind9/named.conf:/etc/bind/named.conf:ro
      - ./data/bind9/named.conf.local:/etc/bind/named.conf.local
      - ./data/bind9/db.root:/etc/bind/db.root
      - ./data/bind9/cache:/var/cache/bind
      - ./data/bind9/records:/var/lib/bind
      - ./data/bind9/named.conf.default-zones:/etc/bind/named.conf.default-zones:ro
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: 172.30.0.3

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
